### ISSUE TITLE
Music Plays, no graphics shown

### ISSUE THREAD

**Issue by TigTog** [wipeout-phantom-edition/wipeout-phantom-edition#1]
Hi,  5700G with RX 6800 XT GPU 32gb Ram.   All extracted and the music plays but i dont see anything on screen.

Alt+Enter moves to windowed mode but again nothing shown.

**Comment by joshman196** [comment]
Same thing happening here. Ryzen 7 5700X and RX 5700XT. If I spam start a bunch of times, I eventually hear the "3, 2, 1, Go" from the game but still nothing shows at all. If I press F8, something manages to actually appear on screen but all it does is just scroll through a bunch of images from the game such as the title screen, font letters, button icons, etc.

**Comment by wipeout-phantom-edition** [comment]
Uh oh. It hasn't been tested on AMD gpus. In `wipeout.cfg` can you try changing `useBindlessTextures "0"` to `useBindlessTextures "1"`.

**Comment by TigTog** [comment]
We're here to help !   :)

**Comment by TigTog** [comment]
useBindlessTextures "0" has no effect

**Comment by joshman196** [comment]
Even after setting bindless textures to "0" there is still a complete black screen.
![VrXDwsc](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/assets/114156648/13ef75af-296e-4ea4-a3b6-e2510f54ee4f)

**Comment by wipeout-phantom-edition** [comment]
Can you start the game with `-console` command line argument and copy/paste the output here.

**Comment by TigTog** [comment]
Here's mine

loading config file "wipeout.cfg"
rapierClassUnlocked "0"
bonusTrackUnlocked "0"
scoreName ""
useBindlessTextures "1"
interpolation "1"
wallCollisionMode "Modern"
screenShake "2"
windowMode "Window"
windowSize "1121" "655"
resolutionMode "Dynamic"
fixedResolution "320" "240"
resolutionScale "1"
aspectRatio "0"
masterVolume "1"
sfxVolume "0.75"
musicVolume "0.4"
musicTrack "-1"
saving config file "wipeout.cfg"
loading game data manifest "phantom/gamedatamanifest".
detecting game data files.
detected 517 game data files, 0 missing.
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon RX 6800 XT
GL_VERSION: 4.3.0 Core Profile Context 23.4.1.230326
initializing audio...
device created: "OpenAL Soft on 4 - DELL S2722QC (3- AMD High Definition Audio Device)"
initializing AudioManager.
loading VAB files "wipeoutgame/wipeout/sound/wipeout.vh" "wipeoutgame/wipeout/sound/wipeout.vb"
loaded 30 VAG progs.
created buffer for SHIP_2_SHIP (Mono16, 14532 samples, 22050hz)
created buffer for ELECTROBOLT (Mono16, 10724 samples, 22050hz)
created buffer for ENG_AIR_INTAKE (Mono16, 33964 samples, 44100hz)
created buffer for ENG_RUMBLE (Mono16, 29764 samples, 44100hz)
created buffer for ENG_THRUST (Mono16, 55972 samples, 44100hz)
created buffer for EXPLOSION_1 (Mono16, 27552 samples, 22050hz)
created buffer for EXPLOSION_2 (Mono16, 32340 samples, 22050hz)
created buffer for SHIP_2_TRACK (Mono16, 21112 samples, 22050hz)
created buffer for MENU_MOVE (Mono16, 5572 samples, 22050hz)
created buffer for MENU_SELECT (Mono16, 5908 samples, 22050hz)
created buffer for MENU_2_MENU (Mono16, 8036 samples, 22050hz)
created buffer for MINE_DROP (Mono16, 11004 samples, 22050hz)
created buffer for MISS_LAUNCH (Mono16, 24248 samples, 22050hz)
created buffer for REMOTE_ENG (Mono16, 25032 samples, 22050hz)
created buffer for POWER_UP (Mono16, 25536 samples, 22050hz)
created buffer for SHIELDS (Mono16, 15456 samples, 22050hz)
created buffer for START_SIREN (Mono16, 31024 samples, 22050hz)
created buffer for TRACTOR_BEAM (Mono16, 20720 samples, 22050hz)
created buffer for TURBULENCE (Mono16, 29680 samples, 22050hz)
created buffer for CROWD (Mono16, 51128 samples, 22050hz)
created buffer for SP_MINES (Mono16, 32592 samples, 44100hz)
created buffer for SP_MISSILE (Mono16, 32340 samples, 44100hz)
created buffer for SP_ROCKET (Mono16, 26068 samples, 44100hz)
created buffer for SP_REVCON (Mono16, 34356 samples, 44100hz)
created buffer for SP_SHOCKWAVE (Mono16, 39032 samples, 44100hz)
created buffer for SP_SPECIAL (Mono16, 35000 samples, 44100hz)
created buffer for SP_3 (Mono16, 34636 samples, 44100hz)
created buffer for SP_2 (Mono16, 35028 samples, 44100hz)
created buffer for SP_1 (Mono16, 36428 samples, 44100hz)
created buffer for SP_GO (Mono16, 39620 samples, 44100hz)
created buffer for NF_SOUND_ID_SCRAPE "phantom/sound/scrape.wav" (Mono16, 38988 samples, 48000hz)
initializing MusicManager.
found music track "music/01 - CoLD SToRAGE - Cairodrome.wav"
found music track "music/02 - CoLD SToRAGE - Cardinal Dance.wav"
found music track "music/03 - CoLD SToRAGE - Cold Comfort.wav"
found music track "music/04 - CoLD SToRAGE - Doh-T.wav"
found music track "music/05 - CoLD SToRAGE - Messij.wav"
found music track "music/06 - CoLD SToRAGE - Oparatique.wav"
found music track "music/07 - CoLD SToRAGE - Tenetative.wav"
found music track "music/08 - CoLD SToRAGE - Trancevaal.wav"
found music track "music/09 - Leftfield - Afro-Ride.wav"
found music track "music/10 - Chemical Brothers, The - Chemical Beats.wav"
found music track "music/11 - Orbital - Wipeout [P.E.T.R.O.L Mix].wav"
initializing graphics...
using bindless textures.
loading shader "phantom/shaders/simplevert.glsl" : "phantom/shaders/simplefrag.glsl"
    compiling vertex shader "phantom/shaders/simplevert.glsl"
    compiling fragment shader "phantom/shaders/simplefrag.glsl"
    uniforms:
        layout(location = 0) uniform (35678) colorTexture [1];
loading shader "phantom/shaders/psxvert.glsl" : "phantom/shaders/psxfrag.glsl"
    compiling vertex shader "phantom/shaders/psxvert.glsl"
         shader compilation error:
ERROR: 0:4: 'filename-based #line' : required extension not requested: GL_GOOGLE_cpp_style_line_directive
ERROR: 0:0: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

loading "wipeoutgame/wipeout/textures/wiptitle.tim" 0.
loaded highscores from "highscores.dat"
saved highscores to "highscores.dat"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (1-10).
loaded "Chemical Beats" "music/10 - Chemical Brothers, The - Chemical Beats.wav" (Stereo16, 292.87sec, 21.98ms)

**Comment by joshman196** [comment]
loading config file "wipeout.cfg"
rapierClassUnlocked "0"
bonusTrackUnlocked "0"
scoreName ""
useBindlessTextures "0"
interpolation "1"
wallCollisionMode "Modern"
screenShake "2"
windowMode "Windowed"
windowSize "1920" "1080"
resolutionMode "Dynamic"
fixedResolution "320" "240"
resolutionScale "1"
aspectRatio "0"
masterVolume "1"
sfxVolume "0.75"
musicVolume "0.4"
musicTrack "-1"
saving config file "wipeout.cfg"
loading game data manifest "phantom/gamedatamanifest".
detecting game data files.
detected 517 game data files, 0 missing.
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon RX 5700 XT
GL_VERSION: 4.3.0 Core Profile Context 23.7.1.230626
initializing audio...
device created: "OpenAL Soft on Speakers (Logitech G935/G933s Gaming Headset)"
initializing AudioManager.
loading VAB files "wipeoutgame/wipeout/sound/wipeout.vh" "wipeoutgame/wipeout/sound/wipeout.vb"
loaded 30 VAG progs.
created buffer for SHIP_2_SHIP (Mono16, 14532 samples, 22050hz)
created buffer for ELECTROBOLT (Mono16, 10724 samples, 22050hz)
created buffer for ENG_AIR_INTAKE (Mono16, 33964 samples, 44100hz)
created buffer for ENG_RUMBLE (Mono16, 29764 samples, 44100hz)
created buffer for ENG_THRUST (Mono16, 55972 samples, 44100hz)
created buffer for EXPLOSION_1 (Mono16, 27552 samples, 22050hz)
created buffer for EXPLOSION_2 (Mono16, 32340 samples, 22050hz)
created buffer for SHIP_2_TRACK (Mono16, 21112 samples, 22050hz)
created buffer for MENU_MOVE (Mono16, 5572 samples, 22050hz)
created buffer for MENU_SELECT (Mono16, 5908 samples, 22050hz)
created buffer for MENU_2_MENU (Mono16, 8036 samples, 22050hz)
created buffer for MINE_DROP (Mono16, 11004 samples, 22050hz)
created buffer for MISS_LAUNCH (Mono16, 24248 samples, 22050hz)
created buffer for REMOTE_ENG (Mono16, 25032 samples, 22050hz)
created buffer for POWER_UP (Mono16, 25536 samples, 22050hz)
created buffer for SHIELDS (Mono16, 15456 samples, 22050hz)
created buffer for START_SIREN (Mono16, 31024 samples, 22050hz)
created buffer for TRACTOR_BEAM (Mono16, 20720 samples, 22050hz)
created buffer for TURBULENCE (Mono16, 29680 samples, 22050hz)
created buffer for CROWD (Mono16, 51128 samples, 22050hz)
created buffer for SP_MINES (Mono16, 32592 samples, 44100hz)
created buffer for SP_MISSILE (Mono16, 32340 samples, 44100hz)
created buffer for SP_ROCKET (Mono16, 26068 samples, 44100hz)
created buffer for SP_REVCON (Mono16, 34356 samples, 44100hz)
created buffer for SP_SHOCKWAVE (Mono16, 39032 samples, 44100hz)
created buffer for SP_SPECIAL (Mono16, 35000 samples, 44100hz)
created buffer for SP_3 (Mono16, 34636 samples, 44100hz)
created buffer for SP_2 (Mono16, 35028 samples, 44100hz)
created buffer for SP_1 (Mono16, 36428 samples, 44100hz)
created buffer for SP_GO (Mono16, 39620 samples, 44100hz)
created buffer for NF_SOUND_ID_SCRAPE "phantom/sound/scrape.wav" (Mono16, 38988 samples, 48000hz)
initializing MusicManager.
found music track "music/01.wav"
found music track "music/02.wav"
found music track "music/03.wav"
found music track "music/04.wav"
found music track "music/05.wav"
found music track "music/06.wav"
found music track "music/07.wav"
found music track "music/08.wav"
initializing graphics...
not using bindless textures.
loading shader "phantom/shaders/simplevert.glsl" : "phantom/shaders/simplefrag.glsl"
    compiling vertex shader "phantom/shaders/simplevert.glsl"
    compiling fragment shader "phantom/shaders/simplefrag.glsl"
    uniforms:
        layout(location = 0) uniform (35678) colorTexture [1];
loading shader "phantom/shaders/psxvert.glsl" : "phantom/shaders/psxfrag.glsl"
    compiling vertex shader "phantom/shaders/psxvert.glsl"
         shader compilation error:
ERROR: 0:4: 'filename-based #line' : required extension not requested: GL_GOOGLE_cpp_style_line_directive
ERROR: 0:0: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

loading "wipeoutgame/wipeout/textures/wiptitle.tim" 0.
loaded highscores from "highscores.dat"
saved highscores to "highscores.dat"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (1-10).
loaded "" "music/04.wav" (Stereo16, 313.69sec, 22.37ms)

This is also after setting the bindless textures back to "1" since we ruled that out as the problem.

**Comment by wipeout-phantom-edition** [comment]
It's a shader compilation error. I made a new release will hopefully fix it:
https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/releases/tag/v1.0.65rc6

**Comment by joshman196** [comment]
No change sadly, still have a black screen.

loading config file "wipeout.cfg"
rapierClassUnlocked "0"
bonusTrackUnlocked "0"
scoreName ""
useBindlessTextures "1"
interpolation "1"
wallCollisionMode "Modern"
screenShake "2"
windowMode "DesktopFullscreen"
windowSize "1920" "1080"
resolutionMode "Dynamic"
fixedResolution "320" "240"
resolutionScale "1"
aspectRatio "0"
masterVolume "1"
sfxVolume "0.75"
musicVolume "0.4"
musicTrack "-1"
saving config file "wipeout.cfg"
loading game data manifest "phantom/gamedatamanifest".
detecting game data files.
detected 517 game data files, 0 missing.
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon RX 5700 XT
GL_VERSION: 4.3.0 Core Profile Context 23.7.1.230626
initializing audio...
device created: "OpenAL Soft on Speakers (Logitech G935/G933s Gaming Headset)"
initializing AudioManager.
loading VAB files "wipeoutgame/wipeout/sound/wipeout.vh" "wipeoutgame/wipeout/sound/wipeout.vb"
loaded 30 VAG progs.
created buffer for SHIP_2_SHIP (Mono16, 14532 samples, 22050hz)
created buffer for ELECTROBOLT (Mono16, 10724 samples, 22050hz)
created buffer for ENG_AIR_INTAKE (Mono16, 33964 samples, 44100hz)
created buffer for ENG_RUMBLE (Mono16, 29764 samples, 44100hz)
created buffer for ENG_THRUST (Mono16, 55972 samples, 44100hz)
created buffer for EXPLOSION_1 (Mono16, 27552 samples, 22050hz)
created buffer for EXPLOSION_2 (Mono16, 32340 samples, 22050hz)
created buffer for SHIP_2_TRACK (Mono16, 21112 samples, 22050hz)
created buffer for MENU_MOVE (Mono16, 5572 samples, 22050hz)
created buffer for MENU_SELECT (Mono16, 5908 samples, 22050hz)
created buffer for MENU_2_MENU (Mono16, 8036 samples, 22050hz)
created buffer for MINE_DROP (Mono16, 11004 samples, 22050hz)
created buffer for MISS_LAUNCH (Mono16, 24248 samples, 22050hz)
created buffer for REMOTE_ENG (Mono16, 25032 samples, 22050hz)
created buffer for POWER_UP (Mono16, 25536 samples, 22050hz)
created buffer for SHIELDS (Mono16, 15456 samples, 22050hz)
created buffer for START_SIREN (Mono16, 31024 samples, 22050hz)
created buffer for TRACTOR_BEAM (Mono16, 20720 samples, 22050hz)
created buffer for TURBULENCE (Mono16, 29680 samples, 22050hz)
created buffer for CROWD (Mono16, 51128 samples, 22050hz)
created buffer for SP_MINES (Mono16, 32592 samples, 44100hz)
created buffer for SP_MISSILE (Mono16, 32340 samples, 44100hz)
created buffer for SP_ROCKET (Mono16, 26068 samples, 44100hz)
created buffer for SP_REVCON (Mono16, 34356 samples, 44100hz)
created buffer for SP_SHOCKWAVE (Mono16, 39032 samples, 44100hz)
created buffer for SP_SPECIAL (Mono16, 35000 samples, 44100hz)
created buffer for SP_3 (Mono16, 34636 samples, 44100hz)
created buffer for SP_2 (Mono16, 35028 samples, 44100hz)
created buffer for SP_1 (Mono16, 36428 samples, 44100hz)
created buffer for SP_GO (Mono16, 39620 samples, 44100hz)
created buffer for NF_SOUND_ID_SCRAPE "phantom/sound/scrape.wav" (Mono16, 38988 samples, 48000hz)
initializing MusicManager.
found music track "music/01.wav"
found music track "music/02.wav"
found music track "music/03.wav"
found music track "music/04.wav"
found music track "music/05.wav"
found music track "music/06.wav"
found music track "music/07.wav"
found music track "music/08.wav"
initializing graphics...
using bindless textures.
loading shader "phantom/shaders/simplevert.glsl" : "phantom/shaders/simplefrag.glsl"
    compiling vertex shader "phantom/shaders/simplevert.glsl"
    compiling fragment shader "phantom/shaders/simplefrag.glsl"
    uniforms:
        layout(location = 0) uniform (35678) colorTexture [1];
loading shader "phantom/shaders/psxvert.glsl" : "phantom/shaders/psxfrag.glsl"
    compiling vertex shader "phantom/shaders/psxvert.glsl"
    compiling fragment shader "phantom/shaders/psxfrag.glsl"
         shader compilation error:
ERROR: 0:30: 'sampler2D' : sampler-constructor requires the input to be ivec2 or uvec2
ERROR: 0:30: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

loading "wipeoutgame/wipeout/textures/wiptitle.tim" 0.
window size changed: 2560x1440
loaded highscores from "highscores.dat"
saved highscores to "highscores.dat"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (1-10).
loaded "" "music/07.wav" (Stereo16, 324.48sec, 28.82ms)

**Comment by TigTog** [comment]
Latest release and useBindlessTextures "0" works !

**Comment by joshman196** [comment]
Ah, bindless textures at 0 does work for me as well actually.

**Comment by wipeout-phantom-edition** [comment]
But the new release does not work with useBindlessTextures enabled?

**Comment by joshman196** [comment]
That's correct, it's still a black screen with bindless textures set to "1". My console output from above is the result of that.

**Comment by TigTog** [comment]
I concur...  "0" = image   "1" = no image

**Comment by wipeout-phantom-edition** [comment]
I attached a file containing two shader files to extract into `wipeout/phantom/shaders` and overwrite existing ones. They may fix bindless textures.
[shaders.zip](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/files/12047992/shaders.zip)

**Comment by joshman196** [comment]
It starts to work but eventually crashes the game and the graphics driver every single time without fail after a second or two of loading the stage. The Terramax stage just loads to a black screen with the HUD visible.
![sMXLFdQ](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/assets/114156648/d3e26535-3961-4c51-b81f-aea83313e1f7)

Here's the console output:

loading config file "wipeout.cfg"
rapierClassUnlocked "0"
bonusTrackUnlocked "0"
scoreName ""
useBindlessTextures "1"
interpolation "1"
wallCollisionMode "Modern"
screenShake "2"
windowMode "Window"
windowSize "1920" "1080"
resolutionMode "Dynamic"
fixedResolution "320" "240"
resolutionScale "1"
aspectRatio "0"
masterVolume "1"
sfxVolume "0.75"
musicVolume "0.4"
musicTrack "-1"
saving config file "wipeout.cfg"
loading game data manifest "phantom/gamedatamanifest".
detecting game data files.
detected 517 game data files, 0 missing.
GL_VENDOR: ATI Technologies Inc.
GL_RENDERER: AMD Radeon RX 5700 XT
GL_VERSION: 4.3.0 Core Profile Context 23.7.1.230626
initializing audio...
device created: "OpenAL Soft on Speakers (Logitech G935/G933s Gaming Headset)"
initializing AudioManager.
loading VAB files "wipeoutgame/wipeout/sound/wipeout.vh" "wipeoutgame/wipeout/sound/wipeout.vb"
loaded 30 VAG progs.
created buffer for SHIP_2_SHIP (Mono16, 14532 samples, 22050hz)
created buffer for ELECTROBOLT (Mono16, 10724 samples, 22050hz)
created buffer for ENG_AIR_INTAKE (Mono16, 33964 samples, 44100hz)
created buffer for ENG_RUMBLE (Mono16, 29764 samples, 44100hz)
created buffer for ENG_THRUST (Mono16, 55972 samples, 44100hz)
created buffer for EXPLOSION_1 (Mono16, 27552 samples, 22050hz)
created buffer for EXPLOSION_2 (Mono16, 32340 samples, 22050hz)
created buffer for SHIP_2_TRACK (Mono16, 21112 samples, 22050hz)
created buffer for MENU_MOVE (Mono16, 5572 samples, 22050hz)
created buffer for MENU_SELECT (Mono16, 5908 samples, 22050hz)
created buffer for MENU_2_MENU (Mono16, 8036 samples, 22050hz)
created buffer for MINE_DROP (Mono16, 11004 samples, 22050hz)
created buffer for MISS_LAUNCH (Mono16, 24248 samples, 22050hz)
created buffer for REMOTE_ENG (Mono16, 25032 samples, 22050hz)
created buffer for POWER_UP (Mono16, 25536 samples, 22050hz)
created buffer for SHIELDS (Mono16, 15456 samples, 22050hz)
created buffer for START_SIREN (Mono16, 31024 samples, 22050hz)
created buffer for TRACTOR_BEAM (Mono16, 20720 samples, 22050hz)
created buffer for TURBULENCE (Mono16, 29680 samples, 22050hz)
created buffer for CROWD (Mono16, 51128 samples, 22050hz)
created buffer for SP_MINES (Mono16, 32592 samples, 44100hz)
created buffer for SP_MISSILE (Mono16, 32340 samples, 44100hz)
created buffer for SP_ROCKET (Mono16, 26068 samples, 44100hz)
created buffer for SP_REVCON (Mono16, 34356 samples, 44100hz)
created buffer for SP_SHOCKWAVE (Mono16, 39032 samples, 44100hz)
created buffer for SP_SPECIAL (Mono16, 35000 samples, 44100hz)
created buffer for SP_3 (Mono16, 34636 samples, 44100hz)
created buffer for SP_2 (Mono16, 35028 samples, 44100hz)
created buffer for SP_1 (Mono16, 36428 samples, 44100hz)
created buffer for SP_GO (Mono16, 39620 samples, 44100hz)
created buffer for NF_SOUND_ID_SCRAPE "phantom/sound/scrape.wav" (Mono16, 38988 samples, 48000hz)
initializing MusicManager.
found music track "music/01.wav"
found music track "music/02.wav"
found music track "music/03.wav"
found music track "music/04.wav"
found music track "music/05.wav"
found music track "music/06.wav"
found music track "music/07.wav"
found music track "music/08.wav"
initializing graphics...
using bindless textures.
loading shader "phantom/shaders/simplevert.glsl" : "phantom/shaders/simplefrag.glsl"
    compiling vertex shader "phantom/shaders/simplevert.glsl"
    compiling fragment shader "phantom/shaders/simplefrag.glsl"
    uniforms:
        layout(location = 0) uniform (35678) colorTexture [1];
loading shader "phantom/shaders/psxvert.glsl" : "phantom/shaders/psxfrag.glsl"
    compiling vertex shader "phantom/shaders/psxvert.glsl"
    compiling fragment shader "phantom/shaders/psxfrag.glsl"
    uniforms:
loading "wipeoutgame/wipeout/textures/wiptitle.tim" 0.
loaded highscores from "highscores.dat"
saved highscores to "highscores.dat"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (1-10).
loaded "" "music/02.wav" (Stereo16, 320.13sec, 22.77ms)
loading "wipeoutgame/wipeout/common/allsh.cmp" 51 (11-61).
loading "wipeoutgame/wipeout/common/pilot.cmp" 9 (62-70).
loading "wipeoutgame/wipeout/common/cdobj.cmp" 1 (71-71).
loading "wipeoutgame/wipeout/common/pad1.cmp" 11 (72-82).
loading "wipeoutgame/wipeout/common/alopt.cmp" 9 (83-91).
loading "wipeoutgame/wipeout/textures/track.cmp" 7 (92-98).
loading "wipeoutgame/wipeout/textures/slider1.tim" 99.
loading "wipeoutgame/wipeout/textures/slide1.tim" 100.
loading "wipeoutgame/wipeout/textures/buttons.cmp" 20 (101-120).
loading "wipeoutgame/wipeout/textures/copyrigt.tim" 121.
loading "wipeoutgame/wipeout/textures/wipeout1.tim" 122.
InitDynamicMem previous dheap used: 659776 bytes.
loading "wipeoutgame/wipeout/textures/load2.tim" 123.
clearing texture manager.
clearing all AudioSources.
sourceCountHighWater: 2
sourceCountHighWaterPersistant: 0
sourceCountHighWaterNonPersistant: 2
loading "wipeoutgame/wipeout/track02/library.cmp" 275 (0-274).
loading "wipeoutgame/wipeout/textures/speedo.tim" 275.
loading "phantom/speedofill.png" 276.
loading "phantom/speedofillthrust.png" 277.
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (278-287).
loading "wipeoutgame/wipeout/common/allsh.cmp" 51 (288-338).
loading "wipeoutgame/wipeout/common/alcol.cmp" 7 (339-345).
loading "wipeoutgame/wipeout/common/rescu.cmp" 7 (346-352).
loading "wipeoutgame/wipeout/track02\scene.cmp" 46 (353-398).
loading "wipeoutgame/wipeout/track02\sky.cmp" 1 (399-399).
loading "wipeoutgame/wipeout/textures/shad1.tim" 400.
loading "wipeoutgame/wipeout/common/wicons.cmp" 9 (401-409).
loading "wipeoutgame/wipeout/textures/dekka.cmp" 2 (410-411).
loading "wipeoutgame/wipeout/common/mine.cmp" 2 (412-413).
loading "wipeoutgame/wipeout/textures/target2.tim" 414.
loading "wipeoutgame/wipeout/common/effects.cmp" 6 (415-420).

**Comment by wipeout-phantom-edition** [comment]
[v1.0.69rc7](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/releases/tag/v1.0.69rc7) will `useBindlessTextures` on startup unless `useBindlessTexturesNonNvidia` is also enabled (its disabled by default). So AMD GPU's should work by default now. This version might also fix the bindless texture incompatibility with AMD GPU's, which can be tested by enabling both `useBindlessTextures` and `useBindlessTexturesNonNvidia` before launching the game.

**Comment by joshman196** [comment]
While it does work in its out-of-the-box configuration (both `useBindlessTextures` and `useBindlessTexturesNonNvidia` set to `"0"`, the update unfortunately did not fix bindless textures (both set to `"1"`). It produces the exact same issue as before. Oh well, but now it's playable for AMD gpu systems without changing any settings which is obviously a good thing.

I have an Intel Arc A380 sitting in my closet, I should probably try testing with that as well.

**Comment by joshman196** [comment]
Alright, I can confirm that the game works fine on the Arc A380. Although the card and/or graphics driver doesn't seem to support bindless textures at all as the console will output "`bindless textures will not be used because they are not supported.`" despite having both `useBindlessTextures` and `useBindlessTexturesNonNvidia` to `"1"`. It still plays fine though, since it's falling back to non-bindless textures anyway.

As a curiosity, I tried the version before any of the updates that stemmed from this issue (v1.0.62rc5) on the A380 and it produced an unplayable white screen there with and without bindless textures turned on. So the fixes you made here actually fixed the game on Intel Arc as well! Neat!

**Comment by wipeout-phantom-edition** [comment]
Thanks for the help! The way bindless textures is implemented is a bit weird and non standard right now (storing texture handles in vertex attributes). Maybe refactoring it will fix things.
