### ISSUE TITLE
Strange pixelated graphival glitch with 1.1.160

### ISSUE THREAD

**Issue by manic232** [wipeout-phantom-edition/wipeout-phantom-edition#20]
I have noticed with v1.1.160 that there is a strange graphical glitch with the fade in, hard to describe kind of pixelated effect at the point that the scenery is fading in, in the distance.  I have an nVidia GPU (4070 ti)

**Comment by wipeout-phantom-edition** [comment]
That sounds like the the GL_ARB_fragment_shader_interlock extension isn't working. It should work fine on Nvidia cards though. Can you paste the output log from the console window here?

**Comment by manic232** [comment]
I'd be happy to but sorry, you'll have to help me out, where do I find that?

**Comment by wipeout-phantom-edition** [comment]
in v1.1.160 if you press alt+enter to go to windowed mode there should be an output window with a bunch of text. With that window selected you can press Ctrl+A to select all, then Ctrl+C copy all the text.

**Comment by manic232** [comment]
OK, as requested.

loading config file "wipeout.cfg"
rapierClassUnlocked "0"
bonusTrackUnlocked "0"
scoreName ""
useBindlessTextures "1"
useBindlessTexturesNonNvidia "0"
useProgrammableBlending "1"
perspectiveCorrect "1"
interpolation "1"
wallCollisionMode "Modern"
newOffTrackDetection "1"
screenShake "2"
windowMode "DesktopFullscreen"
preferredFullscreenMode "DesktopFullscreen"
exclusiveFullscreenResolution "0" "0"
vsync "1"
windowSize "1280" "720"
resolutionMode "Dynamic"
fixedResolution "320" "240"
resolutionScale "1"
aspectRatio "0"
masterVolume "1"
sfxVolume "0.75"
musicVolume "0.4"
musicTrack "-1"
analogDeadzone "0.2"
saving config file "wipeout.cfg"
loading game data manifest "phantom/gamedatamanifest".
detecting game data files.
detected 517 game data files, 0 missing.
using OpenGL Core 4.6
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 536.67
initializing audio...
device created: "OpenAL Soft on Speakers (Sound BlasterX Katana)"
initializing AudioManager.
loading VAB files "wipeoutgame/wipeout/sound/wipeout.vh" "wipeoutgame/wipeout/sound/wipeout.vb"
loaded 30 VAG progs.
created buffer  (Mono16, 14532 samples, 22050hz)
created buffer  (Mono16, 10724 samples, 22050hz)
created buffer  (Mono16, 33964 samples, 44100hz)
created buffer  (Mono16, 29764 samples, 44100hz)
created buffer  (Mono16, 55972 samples, 44100hz)
created buffer  (Mono16, 27552 samples, 22050hz)
created buffer  (Mono16, 32340 samples, 22050hz)
created buffer  (Mono16, 21112 samples, 22050hz)
created buffer  (Mono16, 5572 samples, 22050hz)
created buffer  (Mono16, 5908 samples, 22050hz)
created buffer  (Mono16, 8036 samples, 22050hz)
created buffer  (Mono16, 11004 samples, 22050hz)
created buffer  (Mono16, 24248 samples, 22050hz)
created buffer  (Mono16, 25032 samples, 22050hz)
created buffer  (Mono16, 25536 samples, 22050hz)
created buffer  (Mono16, 15456 samples, 22050hz)
created buffer  (Mono16, 31024 samples, 22050hz)
created buffer  (Mono16, 20720 samples, 22050hz)
created buffer  (Mono16, 29680 samples, 22050hz)
created buffer  (Mono16, 51128 samples, 22050hz)
created buffer  (Mono16, 32592 samples, 44100hz)
created buffer  (Mono16, 32340 samples, 44100hz)
created buffer  (Mono16, 26068 samples, 44100hz)
created buffer  (Mono16, 34356 samples, 44100hz)
created buffer  (Mono16, 39032 samples, 44100hz)
created buffer  (Mono16, 35000 samples, 44100hz)
created buffer  (Mono16, 34636 samples, 44100hz)
created buffer  (Mono16, 35028 samples, 44100hz)
created buffer  (Mono16, 36428 samples, 44100hz)
created buffer  (Mono16, 39620 samples, 44100hz)
created buffer NF_SOUND_ID_SCRAPE "phantom/sound/scrape.wav" (Mono16, 38988 samples, 48000hz)
initializing MusicManager.
found music track "music/01.wav"
found music track "music/02.wav"
found music track "music/03.wav"
found music track "music/04.wav"
found music track "music/05.wav"
found music track "music/06.wav"
found music track "music/07.wav"
found music track "music/08.wav"
initializing graphics...
using bindless textures.
using programmable blending.
loading shader "phantom/shaders/simple.vert.glsl" : "phantom/shaders/simple.frag.glsl"
    compiling vertex shader "phantom/shaders/simple.vert.glsl"
    compiling fragment shader "phantom/shaders/simple.frag.glsl"
    uniforms:
        layout(location = 0) uniform (35678) colorTexture [1];
loading shader "phantom/shaders/psx.vert.glsl" : "phantom/shaders/psx.frag.glsl"
    compiling vertex shader "phantom/shaders/psx.vert.glsl"
    compiling fragment shader "phantom/shaders/psx.frag.glsl"
    uniforms:
        layout(location = 0) uniform (36941) frameBuffer [1];
        layout(location = -1) uniform (5124) perspectiveCorrect [1];
        layout(location = -1) uniform (5124) screenHeight [1];
        layout(location = -1) uniform (5124) screenWidth [1];
loading "wipeoutgame/wipeout/textures/wiptitle.tim" 0.
registered gamepad with id 0 "XInput Controller"
window size changed: 1920x1080
loaded highscores from "highscores.dat"
saved highscores to "highscores.dat"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (1-10).
loaded "" "music/02.wav" (Stereo16, 320.13sec, 32.44ms)
window size changed: 1280x720
loading "wipeoutgame/wipeout/common/allsh.cmp" 51 (11-61).
loading "wipeoutgame/wipeout/common/pilot.cmp" 9 (62-70).
loading "wipeoutgame/wipeout/common/cdobj.cmp" 1 (71-71).
loading "wipeoutgame/wipeout/common/pad1.cmp" 11 (72-82).
loading "wipeoutgame/wipeout/common/alopt.cmp" 9 (83-91).
loading "wipeoutgame/wipeout/textures/track.cmp" 7 (92-98).
loading "wipeoutgame/wipeout/textures/slider1.tim" 99.
loading "wipeoutgame/wipeout/textures/slide1.tim" 100.
loading "wipeoutgame/wipeout/textures/buttons.cmp" 20 (101-120).
loading "wipeoutgame/wipeout/textures/copyrigt.tim" 121.
loading "wipeoutgame/wipeout/textures/wipeout1.tim" 122.
InitDynamicMem previous dheap used: 659712 bytes.
loading "wipeoutgame/wipeout/textures/nload02.tim" 123.
clearing texture manager.
clearing all AudioSources.
sourceCountHighWater: 2
sourceCountHighWaterPersistant: 0
sourceCountHighWaterNonPersistant: 2
loading "wipeoutgame/wipeout/track02/library.cmp" 275 (0-274).
loading "wipeoutgame/wipeout/textures/speedo.tim" 275.
loading "phantom/speedofill.png" 276.
loading "phantom/speedofillthrust.png" 277.
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (278-287).
loading "wipeoutgame/wipeout/common/allsh.cmp" 51 (288-338).
loading "wipeoutgame/wipeout/common/alcol.cmp" 7 (339-345).
loading "wipeoutgame/wipeout/common/rescu.cmp" 7 (346-352).
loading "wipeoutgame/wipeout/track02\scene.cmp" 46 (353-398).
loading "wipeoutgame/wipeout/track02\sky.cmp" 1 (399-399).
loading "wipeoutgame/wipeout/textures/shad1.tim" 400.
loading "wipeoutgame/wipeout/common/wicons.cmp" 9 (401-409).
loading "wipeoutgame/wipeout/textures/dekka.cmp" 2 (410-411).
loading "wipeoutgame/wipeout/common/mine.cmp" 2 (412-413).
loading "wipeoutgame/wipeout/textures/target2.tim" 414.
loading "wipeoutgame/wipeout/common/effects.cmp" 6 (415-420).
loaded "" "music/07.wav" (Stereo16, 324.48sec, 27.50ms)
InitDynamicMem previous dheap used: 2598556 bytes.
clearing texture manager.
clearing all AudioSources.
sourceCountHighWater: 29
sourceCountHighWaterPersistant: 24
sourceCountHighWaterNonPersistant: 7
saved highscores to "highscores.dat"
saving config file "wipeout.cfg"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (0-9).
loading "wipeoutgame/wipeout/textures/nload04.tim" 10.
clearing texture manager.
clearing all AudioSources.
sourceCountHighWater: 1
sourceCountHighWaterPersistant: 0
sourceCountHighWaterNonPersistant: 1
loading "wipeoutgame/wipeout/track04/library.cmp" 261 (0-260).
loading "wipeoutgame/wipeout/textures/speedo.tim" 261.
loading "phantom/speedofill.png" 262.
loading "phantom/speedofillthrust.png" 263.
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (264-273).
loading "wipeoutgame/wipeout/common/allsh.cmp" 51 (274-324).
loading "wipeoutgame/wipeout/common/alcol.cmp" 7 (325-331).
loading "wipeoutgame/wipeout/common/rescu.cmp" 7 (332-338).
loading "wipeoutgame/wipeout/track04\scene.cmp" 35 (339-373).
loading "wipeoutgame/wipeout/track04\sky.cmp" 1 (374-374).
loading "wipeoutgame/wipeout/textures/shad1.tim" 375.
loading "wipeoutgame/wipeout/common/wicons.cmp" 9 (376-384).
loading "wipeoutgame/wipeout/textures/dekka.cmp" 2 (385-386).
loading "wipeoutgame/wipeout/common/mine.cmp" 2 (387-388).
loading "wipeoutgame/wipeout/textures/target2.tim" 389.
loading "wipeoutgame/wipeout/common/effects.cmp" 6 (390-395).
loaded "" "music/02.wav" (Stereo16, 320.13sec, 27.05ms)
InitDynamicMem previous dheap used: 1840938 bytes.
clearing texture manager.
clearing all AudioSources.
sourceCountHighWater: 22
sourceCountHighWaterPersistant: 20
sourceCountHighWaterNonPersistant: 2
saved highscores to "highscores.dat"
loading "wipeoutgame/wipeout/textures/drfonts.cmp" 10 (0-9).
loading "wipeoutgame/wipeout/common/allsh.cmp" 51 (10-60).
loading "wipeoutgame/wipeout/common/pilot.cmp" 9 (61-69).
loading "wipeoutgame/wipeout/common/cdobj.cmp" 1 (70-70).
loading "wipeoutgame/wipeout/common/pad1.cmp" 11 (71-81).
loading "wipeoutgame/wipeout/common/alopt.cmp" 9 (82-90).
loading "wipeoutgame/wipeout/textures/track.cmp" 7 (91-97).
loading "wipeoutgame/wipeout/textures/slider1.tim" 98.
loading "wipeoutgame/wipeout/textures/slide1.tim" 99.
loading "wipeoutgame/wipeout/textures/buttons.cmp" 20 (100-119).
loading "wipeoutgame/wipeout/textures/copyrigt.tim" 120.
loading "wipeoutgame/wipeout/textures/wipeout1.tim" 121.
loaded "" "music/04.wav" (Stereo16, 313.69sec, 26.55ms)

**Comment by wipeout-phantom-edition** [comment]
Thanks for that. Please try [v1.1.168](https://github.com/wipeout-phantom-edition/wipeout-phantom-edition/releases/tag/v1.1.168), hopefully it fixes the issue. I suspect that [this was the problem](https://forums.developer.nvidia.com/t/windows-possible-driver-bug-fragment-shader-interlock-has-almost-no-effect-on-rtx-gpu-driver/79752/2) since it works ok on my 1080 TI, but not on your RTX card.

**Comment by manic232** [comment]
You are a top man! I can confirm that 1.1.168 fixes that issue. Well done and thank you! I absolutely love this port. I have been dreaming of a port like this for years, being a total wipeout fan boy and I nearly spat out my cornflakes when I read about this amazing project. Thank you so much for creating it and for you continuing support.
