### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by mrlionx** [wipeout-phantom-edition/wipeout-phantom-edition#3]
Hello!  When I launch the game it launches at a black screen.  I can hear audio and I can also use my Xbox controller as I hear the controller navigating the main menu.  I have an AMD RX6700.

**Comment by wipeout-phantom-edition** [comment]
Do you know what version you downloaded? If you downloaded it 15 or more hours ago, try the latest version.

**Comment by mrlionx** [comment]
I downloaded the release that was released 3 hours ago, the version I had was from this morning.  It works now.  Thank you!
