### ISSUE TITLE
Option to disable the new particle effects?

### ISSUE THREAD

**Issue by Tasosgemah** [wipeout-phantom-edition/wipeout-phantom-edition#31]
The new collision particle effects aren't very good IMO. The "scratching" effect at the point of impact continues to be visible even after you get away from an object and fades away very slowly. It looks wrong and distracting. 

But even if it looked good, it's still something that's added and doesn't exist in the original. Which, IMO, should be optional in case you want a more authentic look and want to disable it.

I think it would be best if all these little things that are added (or going to be added in the future) had a toggle option or at least a line in the cfg to enable/disable.

**Comment by leRAFs** [comment]
In first person view it’s even more wrong and distracting.
I agree that it would be great to be able to toggle the option.

**Comment by Tasosgemah** [comment]
Newer version has improved the timing of the particles and the effect seems much less distracting now. It can also be disabled. So i'm closing this.
