### ISSUE TITLE
Gamepad config: increase analog stick dead zone, or make it configurable

### ISSUE THREAD

**Issue by ronjouch** [wipeout-phantom-edition/wipeout-phantom-edition#7]
Hi! I game on an old xbox360 controller with analog stick drift (a very common thing for old gamepads; sticks never rest back to a proper x=0,y=0 position), causing the ship to slightly turn when I don't mean to.

Could you:

- A. Either increase the analog stick dead zone (if you have already defined one) ...
- B. ... or add one and make it configurable

A default "dead zone" value of 25% is typical, and it's always best to let it be configurable, to accommodate people who want to increase it (because of a janky controller), or decrease it (if you have a fresh controller and want max. precision).

---

This issue aside, 👏👏👏 excellent sourceport. I just finished a first Venom championship, the game is buttery smooth, zero issue to report, `Modern` wall collision is a godsend, and your choice of defaults is perfect. v1.0.72rc8 / Windows 10 / Nvidia. Thanks a loooooooooot for your work, it brought back fond memories 😊♥️.

**Comment by wipeout-phantom-edition** [comment]
The next release will have `analogDeadzone` configurable in `wipeout.cfg`. I've set the default to `0.2` (previously it was `0.125`).

**Comment by ronjouch** [comment]
Fantasbulous, thanks!!! Closing, will confirm when next release ships, and reopen if needs be. Take care.
