### ISSUE TITLE
Xbox One controller not working with supplied SDL2.dll, fixed with newer DLL from SDL2 project

### ISSUE THREAD

**Issue by YesterPlay80** [wipeout-phantom-edition/wipeout-phantom-edition#9]
Great work with this port, thank you! Just a note though:

Out of the box the port wouldn't work at all with my Xbox One controller, I fixed that by downloading the latest stable x64 SDL2.dll from https://github.com/libsdl-org/SDL/releases/tag/release-2.28.1 and copying it into the source port folder, overwriting the existing one of course. Voilà, working controller! :D So maybe you just have to update your SDL2 libraries or something similar.

**Comment by wipeout-phantom-edition** [comment]
Thanks for testing this. The next version will use SDL 2.28.1.
